---- ~/.config/nvim/lua/Smini/init.lua
--local mm = require 'Smappings.engine'
--
---- keep original
--local _set = mm.set_layout
--
--mm.set_layout = function(layout)
--  _set(layout)
--
--  if layout == 'qwerty' then
--    require('mini.ai').setup {
--      mappings = {
--        -- QWERTY defaults
--        inside = 'i',
--        around_next = 'an',
--        inside_next = 'in',
--        around_last = 'al',
--        inside_last = 'il',
--      },
--    }
--  else -- Colemak
--    require('mini.ai').setup {
--      mappings = {
--        inside = 't',
--        around_next = 'ak',
--        inside_next = 'tk',
--        around_last = 'ai',
--        inside_last = 'ti',
--      },
--    }
--  end
--end
--
---- reapply once plugins are loaded
--vim.api.nvim_create_autocmd('User', {
--  pattern = 'LazyDone',
--  callback = function()
--    mm.set_layout(mm.layout)
--  end,
--})
----require('mini.surround').setup()
vim.keymap.set({ 'o', 'x' }, 'i', '<Nop>')
